import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import { SmartlookProvider } from '@/components/smartlook/smartlook-provider'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { Analytics } from "@vercel/analytics/react"
import './globals.css'
import { ReactQueryProvider } from './react-query-provider'

export const metadata = {
  title: 'Usdcclaimer',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Usdcclaimer Program', path: '/usdcclaimer' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head title='Claim USDC'>
        <meta name="disable-grammarly-extension" content="true" />
      </head>

      <body suppressHydrationWarning>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <SmartlookProvider />
              {children}
              <Analytics />
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
